# Generated by Django 4.1.7 on 2023-04-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ququ', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='QuquBrandOld',
        ),
        migrations.DeleteModel(
            name='QuquBrandOld2',
        ),
    ]
